apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kbyqyckkz-python
  janus-idp.io/tekton: kbyqyckkz-python
  backstage.io/kubernetes-id: kbyqyckkz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kbyqyckkz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
